const solarTerms = [
  {
    id: 1,
    name: '立春',
    angle: 315,
    color: '#B8D4E8',
    daylight: -0.71,
    bg_keyword: 'nature sprouting green buds spring thaw',
    long_description:
      '黄经行至315度，东风送暖，冰雪消融。古人云“立春三日，百草回芽”，大地阳气初升，柳条吐青，蛰虫将醒。农事上宜修农具、备良种，忌大动土木伤地脉；民间有咬春、打春牛之俗，以祈一年稼穑顺遂、仓廪充盈。',
    metaphysics: {
      yee: ['宜·立志规划', '宜·晚睡早起', '宜·食辛甘发散', '宜·出门寻绿'],
      jee: ['忌·大怒伤肝', '忌·过早减衣', '忌·久坐不动', '忌·盲目进补'],
      lucky_direction: '财神正东 / 喜神西南',
      lucky_hours: '寅时、卯时、午时',
    },
  },
  {
    id: 2,
    name: '雨水',
    angle: 330,
    color: '#9EC9E0',
    daylight: -0.50,
    bg_keyword: 'gentle spring rain mist farmland drizzle',
    long_description:
      '此时天一生水，降水渐增而寒气未退，云霭低垂，润物无声。雁北归，草木萌动，农谚云“雨水节，农事忙”，宜耙田保墒、施基肥，忌过早浸种致烂秧。江南烟雨迷蒙，北方则待解冻，万物在湿暖交替中悄然换色。',
    metaphysics: {
      yee: ['宜·疏肝健脾', '宜·温水润燥', '宜·整理庭院', '宜·温和缓行'],
      jee: ['忌·情绪波动', '忌·过食生冷', '忌·冒雨受寒', '忌·熬夜耗气'],
      lucky_direction: '财神正北 / 喜神东南',
      lucky_hours: '卯时、辰时、未时',
    },
  },
  {
    id: 3,
    name: '惊蛰',
    angle: 345,
    color: '#7DBF9A',
    daylight: -0.26,
    bg_keyword: 'spring thunder lightning awakening insects',
    long_description:
      '春雷乍动，蛰虫惊起，桃花始华，黄鹂鸣。阳气升发，病毒易行，宜早睡早起、疏肝理气；田间进入春耕关键期，宜播种豆类、整治沟渠，忌伐木伤禽。农人闻雷即知：一年最忙的时节，已在门楣之外。',
    metaphysics: {
      yee: ['宜·早起伸展', '宜·清淡饮食', '宜·开窗通风', '宜·植树修整'],
      jee: ['忌·急躁动怒', '忌·肥甘厚味', '忌·久坐昏沉', '忌·惊扰过度'],
      lucky_direction: '财神东北 / 喜神正南',
      lucky_hours: '卯时、巳时、申时',
    },
  },
  {
    id: 4,
    name: '春分',
    angle: 0,
    color: '#8FD694',
    daylight: 0.00,
    bg_keyword: 'equinox balance day night equal spring meadow',
    long_description:
      '昼夜均分，阴阳相半，太阳直射赤道，天地中和。燕子归来，油菜花开，麦苗拔节。农事宜中耕除草、平衡水肥，忌偏施氮肥徒长；养生当调和情志，勿大喜大悲。此日乃天地枢机，万物生长之势，自此而盛。',
    metaphysics: {
      yee: ['宜·调和阴阳', '宜·踏青缓行', '宜·食野菜芽', '宜·静心养神'],
      jee: ['忌·大喜大悲', '忌·过食发物', '忌·过劳伤气', '忌·偏湿贪凉'],
      lucky_direction: '财神正东 / 喜神正南',
      lucky_hours: '辰时、午时、酉时',
    },
  },
  {
    id: 5,
    name: '清明',
    angle: 15,
    color: '#6ECF7A',
    daylight: 0.26,
    bg_keyword: 'clear bright sky willow mist tomb sweeping green',
    long_description:
      '气清景明，万物皆显，桐始华，田鼠化鴽。既为慎终追远之节，亦为踏青插柳之时。农谚“清明前后，种瓜点豆”，宜播玉米、棉花，忌大风暴雨伤花；江南采茶正当时，茶香与纸鸢同飞，人间烟火与天地清明相映。',
    metaphysics: {
      yee: ['宜·扫墓祭祖', '宜·踏青插柳', '宜·食青团迎春', '宜·疏风明目'],
      jee: ['忌·野外用火', '忌·过度悲伤', '忌·熬夜伤肝', '忌·赤脚湿地'],
      lucky_direction: '财神东南 / 喜神西南',
      lucky_hours: '巳时、未时、戌时',
    },
  },
  {
    id: 6,
    name: '谷雨',
    angle: 30,
    color: '#4FBF6A',
    daylight: 0.50,
    bg_keyword: 'grain rain tea leaves spring shower abundant',
    long_description:
      '雨生百谷，萍始生，鸣鸠拂羽，戴胜降于桑。降水充沛，秧苗得养，正是“谷雨种谷，万物逢时”。宜插秧、治虫、培土，忌久旱不灌；闽粤采谷雨茶，色翠香幽。此时春末夏初，花事将尽而稼穑正兴，农家无闲人。',
    metaphysics: {
      yee: ['宜·品茗祛湿', '宜·播种备仓', '宜·健脾利水', '宜·轻汗缓行'],
      jee: ['忌·贪凉饮冷', '忌·久处潮湿', '忌·暴饮暴食', '忌·忽视过敏'],
      lucky_direction: '财神正南 / 喜神东北',
      lucky_hours: '辰时、巳时、亥时',
    },
  },
  {
    id: 7,
    name: '立夏',
    angle: 45,
    color: '#7ED957',
    daylight: 0.71,
    bg_keyword: 'early summer lush green heat beginning vibrant',
    long_description:
      '万物并秀，蝼蝈鸣，蚯蚓出，王瓜生。阳气渐盛，暑气初萌，宜养心静气、清淡饮食。农事转入夏管：宜疏果整枝、灌溉保墒，忌暴雨涝田；江南尝新麦，北方防春旱。立夏称人、斗蛋等俗，皆寓祛暑平安、五谷丰登之愿。',
    metaphysics: {
      yee: ['宜·养心安神', '宜·清淡瓜果', '宜·午间小憩', '宜·温水沐浴'],
      jee: ['忌·大汗冲凉', '忌·过食辛辣', '忌·熬夜伤心', '忌·正午剧烈运动'],
      lucky_direction: '财神东南 / 喜神正东',
      lucky_hours: '巳时、午时、未时',
    },
  },
  {
    id: 8,
    name: '小满',
    angle: 60,
    color: '#A8E063',
    daylight: 0.87,
    bg_keyword: 'wheat ears filling summer field golden green',
    long_description:
      '麦粒渐盈而未熟，苦菜秀，靡草死，小暑至。北方麦浪将黄，南方雨水渐丰，江河水位见涨。农谚“小满不满，干断田坎”，宜排涝清淤、防治赤霉病，忌贪懒误收。此时物候微妙，一雨一晴皆关仓廪，农人仰天而慎。',
    metaphysics: {
      yee: ['宜·健脾祛湿', '宜·清补淡食', '宜·关注换季', '宜·护心宁神'],
      jee: ['忌·贪凉饮冰', '忌·过食肥甘', '忌·湿衣久穿', '忌·烦躁动怒'],
      lucky_direction: '财神正南 / 喜神西北',
      lucky_hours: '辰时、巳时、戌时',
    },
  },
  {
    id: 9,
    name: '芒种',
    angle: 75,
    color: '#D4E157',
    daylight: 0.97,
    bg_keyword: 'busy harvest planting barley wheat summer haze',
    long_description:
      '有芒之谷可种，螳螂生，鵙始鸣，反舌无声。收麦与插秧并举，所谓“芒种忙，三两场”，农事达全年最紧。宜抢收抢种、晾晒仓储，忌阴雨霉烂；梅雨季至，衣物生潮，人体亦易感湿困，宜健脾祛湿、稍息劳作。',
    metaphysics: {
      yee: ['宜·抢时农事', '宜·祛湿解暑', '宜·午休养心', '宜·饮绿豆汤'],
      jee: ['忌·过度劳倦', '忌·暴饮冰水', '忌·贪凉风吹', '忌·忽视防潮'],
      lucky_direction: '财神西南 / 喜神正南',
      lucky_hours: '巳时、未时、申时',
    },
  },
  {
    id: 10,
    name: '夏至',
    angle: 90,
    color: '#FFD54F',
    daylight: 1.00,
    bg_keyword: 'sun intense glare yellow summer solstice longest day',
    long_description:
      '日长之至，日影短至，阳气极盛，蝉始鸣，鹿角解，半夏生。北半球白昼最长，暑热将从此后渐深。农事宜灌水降温、防治病虫害，忌正午暴晒劳作；民间食面、祭地，以应阴阳转换。夏至一阴生，盛极而衰，养生贵在“冬病夏治”之机。',
    metaphysics: {
      yee: ['宜·冬病夏治', '宜·食面养生', '宜·避暑静养', '宜·顺时作息'],
      jee: ['忌·正午暴晒', '忌·过贪冷饮', '忌·大怒伤阳', '忌·剧烈运动脱水'],
      lucky_direction: '财神正东 / 喜神正北',
      lucky_hours: '午时、未时、酉时',
    },
  },
  {
    id: 11,
    name: '小暑',
    angle: 105,
    color: '#FFB74D',
    daylight: 0.97,
    bg_keyword: 'summer heat haze cicada humid lotus pond',
    long_description:
      '温风至，蟋蟀居宇，鹰始鸷。暑气初盛而未极，雷雨频繁，荷花盛开，早稻渐黄。宜疏通风、防暑降温、早收早晒，忌贪凉伤胃；农谚“小暑大暑，上蒸下煮”，田间需勤巡堤防涝，人亦当心静自然凉。',
    metaphysics: {
      yee: ['宜·清心降火', '宜·藕菱清暑', '宜·荷风早卧', '宜·防暑备盐'],
      jee: ['忌·空调直吹', '忌·过食油腻', '忌·情绪暴躁', '忌·长途暴晒'],
      lucky_direction: '财神正南 / 喜神东南',
      lucky_hours: '巳时、午时、戌时',
    },
  },
  {
    id: 12,
    name: '大暑',
    angle: 120,
    color: '#FF8A65',
    daylight: 0.87,
    bg_keyword: 'extreme summer heat steam tropical storm crops',
    long_description:
      '大雨时行，腐草为萤，土润溽暑，大雨时行。一年最热，湿热交蒸，农作物进入生长高峰亦易枯萎。宜引水灌溉、遮阴防灼，忌暴雨后闷晒；南方晒伏姜、饮伏茶，以祛湿解暑。此时农人“抢天时”，与烈日争一寸收成。',
    metaphysics: {
      yee: ['宜·伏姜伏茶', '宜·早晚劳作', '宜·祛湿补气', '宜·温水慢饮'],
      jee: ['忌·大汗冲凉', '忌·过热贪冷', '忌·过劳中暑', '忌·情绪激动'],
      lucky_direction: '财神西南 / 喜神正东',
      lucky_hours: '辰时、巳时、未时',
    },
  },
  {
    id: 13,
    name: '立秋',
    angle: 135,
    color: '#E89B5C',
    daylight: 0.71,
    bg_keyword: 'autumn beginning cool breeze golden rice field',
    long_description:
      '凉风至，白露降，寒蝉鸣。暑热未消而秋意已至，梧桐叶落，天地始肃。农谚“立秋见禾晚”，宜防早寒、整地备秋播，忌过早收青粮；民间贴秋膘、晒秋，以补夏耗。此节气如门扉半启，丰收在望而劳作未歇。',
    metaphysics: {
      yee: ['宜·贴膘适度', '宜·润肺养阴', '宜·早睡早起', '宜·缓增衣物'],
      jee: ['忌·过早大补', '忌·贪凉空调', '忌·悲秋伤肺', '忌·盲目泻火'],
      lucky_direction: '财神西北 / 喜神正南',
      lucky_hours: '辰时、申时、戌时',
    },
  },
  {
    id: 14,
    name: '处暑',
    angle: 150,
    color: '#D4896A',
    daylight: 0.50,
    bg_keyword: 'late summer heat ending clear sky harvest calm',
    long_description:
      '暑气将止，鹰乃祭鸟，天地始肃，禾乃登。昼夜温差加大，晨雾渐多，棉花吐絮，稻谷灌浆。宜除草施肥、防治晚疫病，忌贪凉夜露；江南有开渔节，海上风平，人间烟火与渔火同明，秋意渐浓而夏热将散。',
    metaphysics: {
      yee: ['宜·滋阴润燥', '宜·早睡早起', '宜·采菊观云', '宜·轻汗缓行'],
      jee: ['忌·熬夜伤阴', '忌·过食辛辣', '忌·盲目秋补', '忌·夜露贪凉'],
      lucky_direction: '财神正西 / 喜神东南',
      lucky_hours: '巳时、未时、亥时',
    },
  },
  {
    id: 15,
    name: '白露',
    angle: 165,
    color: '#C9A882',
    daylight: 0.26,
    bg_keyword: 'white dew morning mist autumn grass silver',
    long_description:
      '阴气渐凝，露凝而白，鸿雁来，玄鸟归，群鸟养羞。夜凉昼暖，桂香暗浮，棉花采摘正忙。农谚“白露秋分夜，一夜冷一夜”，宜防寒露风、收成熟粮，忌贪青延播；养生当养阴润燥，农事则抢在霜前把秋色锁进仓廪。',
    metaphysics: {
      yee: ['宜·添衣护体', '宜·百合润肺', '宜·温水泡脚', '宜·赏月静心'],
      jee: ['忌·赤膊受凉', '忌·过食生冷', '忌·露身夜行', '忌·悲伤伤肺'],
      lucky_direction: '财神西北 / 喜神西南',
      lucky_hours: '卯时、酉时、戌时',
    },
  },
  {
    id: 16,
    name: '秋分',
    angle: 180,
    color: '#B8956E',
    daylight: 0.00,
    bg_keyword: 'autumn equinox harvest moon chrysanthemum balance',
    long_description:
      '昼夜再均，雷始收声，蛰虫坯户，水始涸。秋高气爽，丹桂飘香，正是“秋收、秋耕、秋种”大忙季。宜深耕晒垡、播种冬小麦，忌阴雨延误；祭月、竖蛋等俗，寓平衡和谐。天地肃杀而不伤生机，农家以汗水换金黄满仓。',
    metaphysics: {
      yee: ['宜·秋祭感恩', '宜·竖蛋祈和', '宜·润燥养胃', '宜·平衡作息'],
      jee: ['忌·偏颇饮食', '忌·过度劳作', '忌·悲郁伤肺', '忌·骤冷骤热'],
      lucky_direction: '财神正东 / 喜神正西',
      lucky_hours: '辰时、午时、酉时',
    },
  },
  {
    id: 17,
    name: '寒露',
    angle: 195,
    color: '#9A8FA8',
    daylight: -0.26,
    bg_keyword: 'cold dew autumn frost chrysanthemum maple mist',
    long_description:
      '露气寒冷，将凝结，菊有黄华，鸿雁来宾。北风渐紧，霜意暗生，山楂红枣成熟，南方收晚稻。宜防冻保温、贮藏果蔬，忌过早脱粒致损；此时登高赏菊、饮菊花酒，以应清寒之气。农人知：寒露过三朝，过秋草皆焦。',
    metaphysics: {
      yee: ['宜·登高赏菊', '宜·暖胃养身', '宜·覆被护足', '宜·菊花酒适度'],
      jee: ['忌·赤膊受寒', '忌·过食寒凉', '忌·久坐不暖', '忌·悲秋伤神'],
      lucky_direction: '财神东北 / 喜神西北',
      lucky_hours: '卯时、巳时、戌时',
    },
  },
  {
    id: 18,
    name: '霜降',
    angle: 210,
    color: '#7E8FA3',
    daylight: -0.50,
    bg_keyword: 'frost crystal texture autumn leaf red bare branches',
    long_description:
      '气肃而凝，露结为霜，豺乃祭兽，草木黄落。初霜可见，万物收藏，柿子挂枝，北方收播收尾。农谚“霜降见霜，米烂陈仓”，宜扫仓晒粮、防鼠防潮，忌忽视防冻；此时养生当温补润肺，田间最后一茬忙碌，为寒冬封存生机。',
    metaphysics: {
      yee: ['宜·温补润肺', '宜·晒秋储粮', '宜·食柿适度', '宜·护膝护踝'],
      jee: ['忌·忽视保暖', '忌·过食生冷', '忌·悲伤郁肺', '忌·晨起猛动'],
      lucky_direction: '财神正北 / 喜神东南',
      lucky_hours: '辰时、申时、亥时',
    },
  },
  {
    id: 19,
    name: '立冬',
    angle: 225,
    color: '#6B8CAE',
    daylight: -0.71,
    bg_keyword: 'winter beginning bare trees cold blue hearth smoke',
    long_description:
      '水始冰，地始冻，雉入大水为蜃，虹藏不见。万物归藏，阳气内守，北方供暖，南方补冬。宜冬灌麦田、贮藏蔬菜，忌盲目修剪伤树；民间吃饺子、酿黄酒，以御寒养阳。立冬如岁之暮鼓，告知农人：休耕有度，蓄力待春。',
    metaphysics: {
      yee: ['宜·温补养肾', '宜·饺子贺冬', '宜·早睡养藏', '宜·冬灌护苗'],
      jee: ['忌·过食燥热', '忌·盲目进补', '忌·熬夜伤肾', '忌·剧烈发汗'],
      lucky_direction: '财神正北 / 喜神西南',
      lucky_hours: '子时、卯时、戌时',
    },
  },
  {
    id: 20,
    name: '小雪',
    angle: 240,
    color: '#5A7FA8',
    daylight: -0.87,
    bg_keyword: 'light snow flurry winter grey sky village',
    long_description:
      '气寒而将雪，雪未大也，虹藏不见，天气上升，闭塞成冬。北风渐劲，落叶殆尽，油菜越冬，农谚“小雪雪满天，来年必丰年”。宜修水利、积肥造肥，忌土壤封冻前失墒；腌菜晒腊，人间烟火升腾，以味觉对抗长夜清寒。',
    metaphysics: {
      yee: ['宜·腌腊备冬', '宜·温酒暖身', '宜·读写静思', '宜·护耳护脚'],
      jee: ['忌·过劳出汗', '忌·抑郁寡欢', '忌·过食咸味', '忌·忽视防滑'],
      lucky_direction: '财神东北 / 喜神正南',
      lucky_hours: '丑时、巳时、亥时',
    },
  },
  {
    id: 21,
    name: '大雪',
    angle: 255,
    color: '#4A6F9C',
    daylight: -0.97,
    bg_keyword: 'heavy snowfall winter landscape white silence forest',
    long_description:
      '积阴为大雪，鶡旦不鸣，虎始交，荔挺出。降雪概率与量级增加，万物潜藏，江河封冻。宜加固棚室、巡查牲畜御寒，忌冰雪压垮设施；北方赏封河、堆雪人，南方亦觉寒意入骨。农事转入管护与筹划，静待一阳来复。',
    metaphysics: {
      yee: ['宜·赏雪围炉', '宜·温肾固元', '宜·检修御寒', '宜·黑豆食养'],
      jee: ['忌·远行冒险', '忌·过食燥热', '忌·久坐不暖', '忌·情志过激'],
      lucky_direction: '财神正西 / 喜神东北',
      lucky_hours: '子时、午时、酉时',
    },
  },
  {
    id: 22,
    name: '冬至',
    angle: 270,
    color: '#3D5F8C',
    daylight: -1.00,
    bg_keyword: 'snow geometry cold blue winter solstice shortest day',
    long_description:
      '日短之至，日影长至，阳气始生，蚯蚓结，麋角解，水泉动。北半球白昼最短，数九寒天自此启。民间祭祖、吃饺子、贺冬，寓否极泰来；农事宜温室管理、检修农具，忌荒废冬管。冬至一阳生，至暗亦藏春信，天地循环，周而复始。',
    metaphysics: {
      yee: ['宜·祭祖团圆', '宜·吃饺子补阳', '宜·早睡晚起', '宜·数九养藏'],
      jee: ['忌·过食燥热', '忌·熬夜伤阳', '忌·大汗漏精', '忌·悲伤损神'],
      lucky_direction: '财神正南 / 喜神西北',
      lucky_hours: '子时、卯时、申时',
    },
  },
  {
    id: 23,
    name: '小寒',
    angle: 285,
    color: '#4A6F9C',
    daylight: -0.97,
    bg_keyword: 'bitter cold ice crystal plum blossom winter dawn',
    long_description:
      '冷气积而为寒，小未甚也，雁北乡，鹊始巢，雉始雊。三九前后，寒意彻骨，梅蕊破香，腊味渐浓。宜加强牲畜饲管、温室补光，忌冰雪出行冒险；农谚“小寒大寒，冷成冰团”，人守炉火，田藏瑞雪，皆盼来岁麦苗青青。',
    metaphysics: {
      yee: ['宜·腊八粥暖', '宜·梅香静心', '宜·暖足护腰', '宜·室内缓动'],
      jee: ['忌·户外久冻', '忌·过食辛辣', '忌·情绪低落', '忌·盲目发汗'],
      lucky_direction: '财神东南 / 喜神正北',
      lucky_hours: '丑时、辰时、戌时',
    },
  },
  {
    id: 24,
    name: '大寒',
    angle: 300,
    color: '#5A7FA8',
    daylight: -0.87,
    bg_keyword: 'deepest winter frost ice river end cycle renewal',
    long_description:
      '寒气之逆极，鸡始乳，征鸟厉疾，水泽腹坚。一年最冷，冰雪坚凝，年味已近，扫尘祭灶。宜完成冬储、检修农机，忌冒寒远行；尾牙、除旧布新，人间热闹与严寒相映。大寒过后即立春，天地将转，农人心中，已隐约听见东风的脚步。',
    metaphysics: {
      yee: ['宜·扫尘辞旧', '宜·备年货暖', '宜·固肾藏精', '宜·围炉守岁'],
      jee: ['忌·冒寒远行', '忌·思虑过重', '忌·过食肥甘', '忌·损耗肾精'],
      lucky_direction: '财神正东 / 喜神西南',
      lucky_hours: '寅时、巳时、亥时',
    },
  },
];
